# Generated by Django 3.0.6 on 2020-06-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='short_name',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
